import Head from "next/head";

export default function Home() {

  return (
    <>
      <Head>
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
        <title>Active E-Commerce CMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <FeatureBlog/>
      <Contact/> */}
    </>
  );
}
