import Head from "next/head";
import Banner from "../src/Components/Home/Banner/Banner";
import ProductSection from "../src/Components/Home/ProductSection/ProductSection";
import CategorySec from "../src/Components/Home/CategorySec/CategorySec/CategorySec";
import BrandSec from "../src/Components/Home/CategorySec/BrandSec/BrandSec";

export default function Home() {

  return (
    <>
      <Head>
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
        <title>Active E-Commerce CMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <ProductSection />
      <div className="grid sm:grid-cols-2 gap-5 mid-container">
        <CategorySec />
        <BrandSec />
      </div>
    </>
  );
}
